/* Generated local data images must bypass remote image optimization. */
/* eslint-disable @next/next/no-img-element */
"use client";
import {useState} from "react";
import Papa from "papaparse";
import JSZip from "jszip";
import {toast} from "sonner";
import {Layers,Upload,Download} from "lucide-react";
import {renderQR,svgURL} from "@/lib/qr/render";
import {Design,defaultDesign} from "@/lib/qr/design";
import {exportBlob,downloadBlob,filename} from "@/lib/export";
import {safeUrl} from "@/lib/payloads";
import DesignControls,{Toggle} from "@/components/generator/controls";
type Row={name:string;value:string;svg?:string;error?:string};
export function parseRows(text:string,csv:boolean):Row[]{if(csv){const parsed=Papa.parse<{name?:string;url?:string;value?:string}>(text,{header:true,skipEmptyLines:"greedy",transformHeader:h=>h.trim().toLowerCase()});if(parsed.errors.length)throw Error("CSV: "+parsed.errors[0].message);if(!parsed.meta.fields?.some(x=>x==="url"||x==="value"))throw Error("CSV needs a url or value column and optional name column.");return parsed.data.map((r,i)=>({name:r.name||"Code "+(i+1),value:r.url||r.value||""}))}return text.split(/\r?\n/).filter(s=>s.trim()).map((value,i)=>({name:"Code "+(i+1),value:value.trim()}))}
export default function Bulk(){
const [text,setText]=useState("https://example.com\nhttps://wikipedia.org"),[csv,setCSV]=useState(false),[urls,setURLs]=useState(true),[design,setDesign]=useState<Design>({...defaultDesign}),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(0);
async function generate(){setError("");setRows([]);setBusy(true);try{const input=parseRows(text,csv);if(!input.length||input.length>100)throw Error("Enter between 1 and 100 rows.");const result:Row[]=[];for(let i=0;i<input.length;i++){const r=input[i];try{if(!r.value||new TextEncoder().encode(r.value).length>2200)throw Error("Empty or too long.");const value=urls?safeUrl(r.value):r.value;result.push({...r,svg:renderQR(value,design).svg})}catch(e){result.push({...r,error:(e as Error).message})}setProgress(i+1);if(i%5===0)await new Promise(resolve=>setTimeout(resolve,0))}setRows(result);toast.success(result.filter(r=>r.svg).length+" QR codes generated")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function zip(){setBusy(true);try{const z=new JSZip();let i=0;for(const r of rows.filter(r=>r.svg)){z.file(String(++i).padStart(3,"0")+"-"+filename(r.name,"svg"),r.svg!)}downloadBlob(await z.generateAsync({type:"blob"}),"qrforge-bulk.zip");toast.success("ZIP downloaded")}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
return <><div className="workspace bulk-workspace"><section className="panel"><div className="section-title"><Layers/><h2>Create in batches</h2></div><p className="subtle">One value per line, or a CSV with name,url columns. Up to 100 codes per batch.</p><Toggle label="CSV input" checked={csv} onChange={setCSV}/><Toggle label="Validate as website URLs" checked={urls} onChange={setURLs}/><label className="field">Values<textarea className="bulk-input" value={text} onChange={e=>setText(e.target.value)} maxLength={250000}/></label><div className="button-row"><label className="secondary file-button"><Upload size={16}/>Upload CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>300000)throw Error("CSV must be below 300 KB.");setText(await f.text());setCSV(true)}catch(err){setError((err as Error).message)}}}/></label><button className="secondary" onClick={()=>downloadBlob(new Blob(["name,url\nMy website,https://example.com\n"],{type:"text/csv"}),"qrforge-template.csv")}>CSV template</button></div><button className="primary full" disabled={busy} onClick={()=>void generate()}>{busy?"Working… "+progress:"Generate batch"}</button>{error&&<p role="alert" className="error">{error}</p>}</section><DesignControls design={design} setDesign={setDesign}/><section className="panel"><h2>Your batch</h2><p className="hint">Exports use the design at generation time. Regenerate to apply design changes.</p><button className="primary full" disabled={busy||!rows.some(r=>r.svg)} onClick={()=>void zip()}><Download size={18}/>Download all as ZIP (SVG)</button>{!rows.length&&<p className="empty">Generated codes will appear here.</p>}<div className="batch-results">{rows.map((r,i)=><article key={i}>{r.svg&&<img src={svgURL(r.svg)} alt={r.name}/>}<div><b>{r.name}</b><p className={r.error?"error":"hint"}>{r.error||r.value}</p>{r.svg&&<button className="secondary" onClick={()=>void exportBlob(r.svg!,design.size,"PNG").then(b=>downloadBlob(b,filename(r.name,"png"))).catch(e=>toast.error(e.message))}>Download PNG</button>}</div></article>)}</div></section></div></>
}
