"use client";
import Link from "next/link";
import {useState} from "react";
import {Code2,Play,Copy} from "lucide-react";
import {utilities,Utility,runTool} from "@/lib/tools";
import {copyText} from "@/lib/export";
import {Choice} from "@/components/generator/controls";
import {toast} from "sonner";
export default function DeveloperTools(){
const [tool,setTool]=useState<Utility>("JSON Formatter"),[input,setInput]=useState('{"hello":"world","madeWith":"QRForge"}'),[second,setSecond]=useState(""),[output,setOutput]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[options,setOptions]=useState<Record<string,string>>({});
const dual=["Text Diff","Contrast Checker","Gradient Generator","Regex Tester"].includes(tool);
async function run(){setBusy(true);setError("");try{setOutput(await runTool(tool,input,second,options))}catch(e){setOutput("");setError((e as Error).message)}finally{setBusy(false)}}
return <div className="developer-layout"><aside className="panel tool-picker"><label className="field">Find a tool<input placeholder="Search tools…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="tool-list">{utilities.filter(t=>t.toLowerCase().includes(search.toLowerCase())).map(t=><button key={t} className={t===tool?"selected":""} onClick={()=>{setTool(t);setOutput("");setError("")}}>{t}</button>)}</div><Link className="secondary full" href="/barcode-generator">Barcode generator</Link><Link className="secondary full" href="/image-tools">Image tools</Link></aside><section className="panel"><div className="section-title"><Code2/><h2>{tool}</h2></div><p className="subtle">Processed in your browser. Your input is never sent to a server.</p>{tool==="JWT Decoder"&&<p className="notice">Decoding a JWT does not verify its signature.</p>}<label className="field">{tool==="Regex Tester"?"Pattern":["UUID Generator","Secure Random String","Lorem Ipsum Generator"].includes(tool)?"Count / length (optional)":"Input"}<textarea className="code-input" spellCheck={false} value={input} onChange={e=>setInput(e.target.value)} maxLength={250000}/></label>{dual&&<label className="field">{tool==="Regex Tester"?"Test string":tool==="Text Diff"?"Changed text":"Second color"}<textarea value={second} onChange={e=>setSecond(e.target.value)} maxLength={250000}/></label>}{tool==="UTM Builder"&&["source","medium","campaign","term","content"].map(k=><label className="field" key={k}>UTM {k}<input value={options[k]||""} onChange={e=>setOptions({...options,[k]:e.target.value})}/></label>)}{tool==="Case Converter"&&<Choice label="Case" value={options.case||"title"} items={["title","upper","lower"]} onChange={v=>setOptions({...options,case:v})}/>} {tool==="Regex Tester"&&<label className="field">Flags<input value={options.flags??"g"} onChange={e=>setOptions({...options,flags:e.target.value})}/></label>}{tool==="Gradient Generator"&&<label className="field">Angle<input type="number" min="0" max="360" value={options.angle||"90"} onChange={e=>setOptions({...options,angle:e.target.value})}/></label>}<button className="primary full" onClick={()=>void run()} disabled={busy}><Play size={16}/>{busy?"Processing…":"Run tool"}</button>{error&&<p role="alert" className="error">{error}</p>}</section><section className="panel"><div className="section-title"><h2>Output</h2><button className="icon-button" title="Copy output" aria-label="Copy output" disabled={!output} onClick={()=>copyText(output).then(()=>toast.success("Copied")).catch(e=>toast.error(e.message))}><Copy size={17}/></button></div>{output?<><pre className="result-box">{output}</pre>{tool==="Gradient Generator"&&<div className="gradient-demo" style={{background:output}}/>}{tool==="UTM Builder"&&<Link className="secondary full" href={"/url-qr-code#url="+encodeURIComponent(output)}>Create QR for this URL</Link>}</>:<p className="empty">Run the tool to see the result.</p>}</section></div>
}
