/* Generated local data images must bypass remote image optimization. */
/* eslint-disable @next/next/no-img-element */
"use client";
import {useState} from "react";
import {Choice,Range} from "@/components/generator/controls";
import {imageFrom,copyText} from "@/lib/export";
import {toast} from "sonner";
export default function Images(){
const [src,setSrc]=useState(""),[format,setFormat]=useState("image/webp"),[width,setWidth]=useState(1024),[quality,setQuality]=useState(85),[ratio,setRatio]=useState(1),[result,setResult]=useState(""),[error,setError]=useState("");
async function file(f?:File){if(!f)return;try{if(!["image/png","image/jpeg","image/webp"].includes(f.type)||f.size>15000000)throw Error("Use a PNG, JPG or WebP smaller than 15 MB.");const url=URL.createObjectURL(f);try{const im=await imageFrom(url);if(im.width*im.height>40000000)throw Error("Image dimensions are too large.");const data=await new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(f)});setSrc(data);setWidth(Math.min(4096,im.width));setRatio(im.height/im.width);setError("");setResult("")}finally{URL.revokeObjectURL(url)}}catch(e){setError((e as Error).message)}}
async function convert(){setError("");try{if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(src)||src.length>21000000)throw Error("Choose an image or paste a PNG/JPG/WebP base64 data URL.");const im=await imageFrom(src);const actualRatio=im.height/im.width,h=Math.round(width*actualRatio);if(width*h>20000000)throw Error("Output exceeds 20 megapixels. Reduce the width.");const canvas=document.createElement("canvas");canvas.width=width;canvas.height=h;const ctx=canvas.getContext("2d")!;if(format==="image/jpeg"){ctx.fillStyle="#fff";ctx.fillRect(0,0,width,h)}ctx.drawImage(im,0,0,width,h);const data=canvas.toDataURL(format,quality/100);if(!data.startsWith("data:"+format))throw Error("This browser cannot encode that format.");setResult(data);setRatio(actualRatio)}catch(e){setError((e as Error).message)}}
return <div className="tool-layout"><section className="panel"><h2>Resize, compress & convert</h2><p className="subtle">Images are processed locally. Aspect ratio is preserved.</p><label className="secondary file-button">Choose image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void file(e.target.files?.[0])}/></label><label className="field">Or paste an image data URL<textarea value={src} onChange={e=>{setSrc(e.target.value);setResult("")}} maxLength={21000000}/></label><label className="field">Output width<input type="number" min={16} max={4096} value={width} onChange={e=>setWidth(Math.min(4096,Math.max(16,+e.target.value||16)))}/></label><label className="field">Format<Choice label="Image format" value={format} onChange={setFormat} items={[{value:"image/png",label:"PNG"},{value:"image/jpeg",label:"JPG"},{value:"image/webp",label:"WebP"}]}/></label>{format!=="image/png"&&<Range label="Quality" value={quality} min={10} max={100} unit="%" onChange={setQuality}/>}<button className="primary full" onClick={()=>void convert()}>Process image</button>{error&&<p className="error">{error}</p>}</section><section className="panel"><h2>Result</h2>{result?<><img className="image-result" src={result} alt="Converted image"/><p className="hint">{width} × {Math.round(width*ratio)} · approximately {Math.round(result.length*.75/1024)} KB</p><div className="button-row"><button className="primary" onClick={()=>{const a=document.createElement("a");a.href=result;a.download="qrforge-image."+format.split("/")[1];a.click()}}>Download image</button><button className="secondary" onClick={()=>copyText(result).then(()=>toast.success("Image base64 copied")).catch(e=>toast.error(e.message))}>Copy Base64</button></div></>:<p className="empty">Your processed image will appear here.</p>}{src&&<button className="secondary full" onClick={()=>copyText(src).then(()=>toast.success("Original image Base64 copied")).catch(e=>toast.error(e.message))}>Copy original Base64</button>}</section></div>
}
