/* Generated local data images must bypass remote image optimization. */
/* eslint-disable @next/next/no-img-element */
"use client";
import {useState,useId} from "react";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Switch} from "@/components/ui/switch";
import {Slider} from "@/components/ui/slider";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {RotateCcw,ImagePlus,ChevronDown,Upload,Copy} from "lucide-react";
import {Design,defaultDesign,frames,applyFrame,importDesign} from "@/lib/qr/design";
import {loadLogo,copyText} from "@/lib/export";
import {toast} from "sonner";
export function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:(string|{value:string;label:string})[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(x=>typeof x==="string"?<SelectItem key={x} value={x}>{x}</SelectItem>:<SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
export function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){const id=useId();return <div className="toggle-row"><label htmlFor={id}>{label}</label><Switch id={id} checked={checked} onCheckedChange={onChange}/></div>}
export function Range({label,value,min,max,onChange,unit=""}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void;unit?:string}){return <div className="range"><div className="control-heading">{label}<span>{value}{unit}</span></div><Slider aria-label={label} value={[value]} min={min} max={max} step={1} onValueChange={v=>onChange(v[0])}/></div>}
export function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label>{label}<div className="color-input"><input aria-label={label} type="color" value={value} onChange={e=>onChange(e.target.value)}/><span>{value.toUpperCase()}</span></div></label>}
export default function DesignControls({design:d,setDesign,initialTab="style"}:{design:Design;setDesign:(d:Design)=>void;initialTab?:string}){
const [advanced,setAdvanced]=useState(false),[search,setSearch]=useState(""),[category,setCategory]=useState("All"),[tab,setTab]=useState(initialTab);
const update=(patch:Partial<Design>)=>setDesign({...d,...patch});
async function upload(f?:File){if(!f)return;try{update({logo:await loadLogo(f),correction:"H"});toast.success("Logo added")}catch(e){toast.error((e as Error).message)}}
return <section className="panel design-panel"><div className="section-title"><span className="step">2</span><h2>Make it yours</h2><button className="icon-button" title="Reset design" aria-label="Reset design" onClick={()=>{setDesign({...defaultDesign});toast.success("Design reset")}}><RotateCcw size={16}/></button></div><Tabs value={tab} onValueChange={setTab}><TabsList className="design-tabs"><TabsTrigger value="style">Style</TabsTrigger><TabsTrigger value="logo">Logo</TabsTrigger><TabsTrigger value="frame">Frame</TabsTrigger></TabsList><TabsContent value="style">
<div className="control-heading">Colors<span>{d.gradient?"Gradient":"Solid color"}</span></div><div className="color-row"><Color label="Foreground" value={d.foreground} onChange={v=>update({foreground:v,eyeColor:v})}/><Color label="Background" value={d.background} onChange={v=>update({background:v})}/></div>
<div className="control-heading palette-title">Quick palettes</div><div className="palettes">{["#181d29","#1957cc","#305749","#a45135","#744bb1","#bd427b"].map(c=><button aria-label={"Use "+c} key={c} style={{background:c}} onClick={()=>update({foreground:c,eyeColor:c})}/>)}</div>
<div className="rule"/><div className="control-heading">Pattern</div><div className="pattern-options">{["Square","Rounded","Dots"].map((s,i)=><button key={s} className={d.pattern===s?"selected":""} onClick={()=>update({pattern:s as Design["pattern"]})}><span className={"pattern-swatch p"+i}>{Array.from({length:9},(_,j)=><i key={j}/>)}</span>{s}</button>)}</div>
<div className="control-heading">Corners</div><div className="corner-options">{["Square","Rounded","Dots"].map((s,i)=><button title={s+" corners"} aria-label={s+" corners"} key={s} className={d.corner===s?"selected":""} onClick={()=>update({corner:s as Design["corner"]})}><span style={{borderRadius:i*7}}/></button>)}</div><div className="rule"/><button className="advanced" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}>Advanced settings <ChevronDown size={16}/></button>
{advanced&&<div className="advanced-body"><Toggle label="Transparent background" checked={d.transparent} onChange={v=>update({transparent:v})}/><Toggle label="Gradient ink" checked={d.gradient} onChange={v=>update({gradient:v})}/>{d.gradient&&<><Color label="Second gradient color" value={d.gradientColor} onChange={v=>update({gradientColor:v})}/><Range label="Gradient angle" value={d.angle} min={0} max={360} unit="°" onChange={v=>update({angle:v})}/></>}
<label className="field">All patterns<Choice label="All patterns" value={d.pattern} onChange={v=>update({pattern:v as Design["pattern"]})} items={["Square","Rounded","Dots","Classy","Classy Rounded","Extra Rounded"]}/></label>
<label className="field">Inner eye style<Choice label="Inner eye style" value={d.eye} onChange={v=>update({eye:v as Design["eye"]})} items={["Square","Rounded","Dots"]}/></label><Color label="Eye color" value={d.eyeColor} onChange={v=>update({eyeColor:v})}/><Range label="Quiet zone" value={d.margin} min={0} max={12} unit=" modules" onChange={v=>update({margin:v})}/>
<label className="field">Error correction<Choice label="Error correction" value={d.logo?"H":d.correction} onChange={v=>update({correction:v as Design["correction"]})} items={["L","M","Q","H"]}/></label>{d.logo&&<p className="hint">High correction is enforced when a logo is present.</p>}
<button className="secondary full" onClick={()=>copyText(JSON.stringify({...d,logo:""},null,2)).then(()=>toast.success("Design copied without logo")).catch(e=>toast.error(e.message))}><Copy size={15}/>Copy design settings</button><label className="secondary file-button"><Upload size={15}/>Import design JSON<input type="file" accept=".json,application/json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>4000000)throw Error("Design file is too large.");setDesign(importDesign(await f.text()));toast.success("Design imported")}catch(err){toast.error((err as Error).message)}}}/></label></div>}
</TabsContent><TabsContent value="logo"><div className="upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0])}}><ImagePlus size={28}/><h3>A familiar finishing touch</h3><p>Drop your logo here or choose a file.</p><label className="secondary file-button">Choose logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])}/></label><p className="hint">PNG, JPG or WebP · up to 3 MB</p></div>{d.logo&&<><img className="logo-thumb" src={d.logo} alt="Uploaded logo"/><button className="secondary full" onClick={()=>update({logo:""})}>Remove logo</button><Range label="Logo size" value={d.logoSize} min={8} max={25} unit="%" onChange={v=>update({logoSize:v})}/><Range label="Logo padding" value={d.logoPadding} min={0} max={8} onChange={v=>update({logoPadding:v})}/><Toggle label="Background plate" checked={d.logoPlate} onChange={v=>update({logoPlate:v})}/><Toggle label="Rounded logo" checked={d.logoRounded} onChange={v=>update({logoRounded:v})}/></>}</TabsContent>
<TabsContent value="frame"><label className="field">Find a frame<input placeholder="Search frames…" value={search} onChange={e=>setSearch(e.target.value)}/></label><Choice label="Frame category" value={category} onChange={setCategory} items={["All",...new Set(frames.map(f=>f.category))]}/><div className="frame-grid">{frames.filter(f=>(category==="All"||f.category===category)&&(f.name+" "+f.text).toLowerCase().includes(search.toLowerCase())).map(f=><button key={f.id} className={d.frame===f.id?"frame-tile selected":"frame-tile"} onClick={()=>setDesign(applyFrame(d,f.id))}><span aria-hidden="true" className={"mini-frame "+f.style}><span className="mini-code">▦</span>{f.style!=="none"&&<small>{f.text}</small>}</span><span>{f.name}</span></button>)}</div>
{d.frame!=="none"&&<><label className="field">Frame text<input maxLength={60} value={d.frameText} onChange={e=>update({frameText:e.target.value})}/></label><div className="color-row"><Color label="Frame color" value={d.frameColor} onChange={v=>update({frameColor:v})}/><Color label="Background" value={d.frameBackground} onChange={v=>update({frameBackground:v})}/><Color label="Text color" value={d.textColor} onChange={v=>update({textColor:v})}/></div><Range label="Border" value={d.frameBorder} min={0} max={12} onChange={v=>update({frameBorder:v})}/><Range label="Radius" value={d.frameRadius} min={0} max={60} onChange={v=>update({frameRadius:v})}/><Range label="Font size" value={d.fontSize} min={12} max={36} onChange={v=>update({fontSize:v})}/><Range label="Padding" value={d.framePadding} min={8} max={50} onChange={v=>update({framePadding:v})}/><Range label="Spacing" value={d.spacing} min={0} max={30} onChange={v=>update({spacing:v})}/><label className="field">Font weight<Choice label="Font weight" value={d.fontWeight} onChange={v=>update({fontWeight:v as Design["fontWeight"]})} items={["400","600","700"]}/></label><label className="field">Icon<Choice label="Frame icon" value={d.icon} onChange={v=>update({icon:v as Design["icon"]})} items={["none","arrow","scan","heart"]}/></label></>}
</TabsContent></Tabs></section>
}
