import {z} from "zod";
const color=z.string().regex(/^#[0-9a-fA-F]{6}$/);
export const designSchema=z.object({version:z.literal(1),foreground:color,background:color,transparent:z.boolean(),gradient:z.boolean(),gradientColor:color,angle:z.number().min(0).max(360),pattern:z.enum(["Square","Rounded","Dots","Classy","Classy Rounded","Extra Rounded"]),corner:z.enum(["Square","Rounded","Dots"]),eye:z.enum(["Square","Rounded","Dots"]),eyeColor:color,margin:z.number().min(0).max(12),correction:z.enum(["L","M","Q","H"]),size:z.number().int().min(256).max(4096),logo:z.string().max(4000000).refine(v=>!v||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v),"Only raster data images are allowed"),logoSize:z.number().min(8).max(25),logoPadding:z.number().min(0).max(8),logoRounded:z.boolean(),logoPlate:z.boolean(),frame:z.string().max(50),frameText:z.string().max(60),frameColor:color,frameBackground:color,textColor:color,frameBorder:z.number().min(0).max(12),frameRadius:z.number().min(0).max(60),fontSize:z.number().min(12).max(36),fontWeight:z.enum(["400","600","700"]),framePadding:z.number().min(8).max(50),spacing:z.number().min(0).max(30),icon:z.enum(["none","arrow","scan","heart"])});
export type Design=z.infer<typeof designSchema>;
export const defaultDesign:Design={version:1,foreground:"#181d29",background:"#ffffff",transparent:false,gradient:false,gradientColor:"#1957cc",angle:45,pattern:"Square",corner:"Square",eye:"Square",eyeColor:"#181d29",margin:4,correction:"M",size:1024,logo:"",logoSize:18,logoPadding:3,logoRounded:true,logoPlate:true,frame:"none",frameText:"SCAN ME",frameColor:"#181d29",frameBackground:"#ffffff",textColor:"#ffffff",frameBorder:3,frameRadius:20,fontSize:21,fontWeight:"600",framePadding:20,spacing:10,icon:"none"};
export type Frame={id:string;name:string;category:string;text:string;style:"none"|"simple"|"minimal"|"rounded"|"modern"|"card"|"badge"|"ticket"|"poster"};
export const frames:Frame[]=[{id:"none",name:"No frame",category:"Minimal",text:"",style:"none"},...["Simple","Minimal","Rounded","Modern","Card","Badge","Ticket","Poster"].map(name=>({id:name.toLowerCase(),name,category:"Minimal",text:"SCAN ME",style:name.toLowerCase() as Frame["style"]})),...[
["scan-me","Scan me","Personal","SCAN ME"],["scan-here","Scan here","Personal","SCAN HERE"],["scan-now","Scan now","Marketing","SCAN NOW"],["open-link","Open link","Business","OPEN LINK"],["website","Visit website","Business","VISIT WEBSITE"],["connect","Connect","Social","CONNECT"],["wifi","Join Wi-Fi","Wi-Fi","JOIN WI-FI"],["menu","View menu","Restaurant","VIEW MENU"],["order","Order now","Restaurant","ORDER NOW"],["pay","Pay now","Payment","PAY NOW"],["contact","Contact me","Personal","CONTACT ME"],["save-contact","Save contact","Business","SAVE CONTACT"],["whatsapp","WhatsApp me","Social","WHATSAPP ME"],["location","View location","Personal","VIEW LOCATION"],["directions","Get directions","Business","GET DIRECTIONS"],["app","Download app","Business","DOWNLOAD APP"],["register","Register now","Events","REGISTER NOW"],["event","Join event","Events","JOIN EVENT"],["offer","Get offer","Marketing","GET OFFER"],["coupon","Claim coupon","Marketing","CLAIM COUPON"]
].map(([id,name,category,text],i)=>({id,name,category,text,style:["rounded","modern","card","badge","ticket","poster"][i%6] as Frame["style"]}))];
export function applyFrame(d:Design,id:string):Design{const f=frames.find(x=>x.id===id);if(!f)throw Error("Unknown frame.");return {...d,frame:id,frameText:f.text}}
export function importDesign(text:string){const d=designSchema.parse(JSON.parse(text));if(!frames.some(f=>f.id===d.frame))throw Error("Unknown frame.");return d}
export function luminance(hex:string){const v=hex.slice(1).match(/../g)!.map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722}
export function contrast(a:string,b:string){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
export function quality(d:Design,modules:number){const warnings:string[]=[];const c=Math.min(contrast(d.foreground,d.background),contrast(d.eyeColor,d.background),d.gradient?contrast(d.gradientColor,d.background):100);if(c<4.5)warnings.push("Increase foreground, gradient and eye contrast against the background.");if(d.margin<4)warnings.push("Use a quiet zone of at least four modules.");if(d.transparent)warnings.push("Place the transparent code on a plain, light background.");if(d.logo&&d.logoSize>20)warnings.push("Reduce the logo below 20% for more reliable scanning.");if(modules>65)warnings.push("Dense code: use a larger print size and test from your scanning distance.");if(d.pattern!=="Square")warnings.push("Test the styled pattern with your intended scanners.");return {label:warnings.length>2||c<3||d.margin<2?"Risky":warnings.length?"Good":"Excellent",warnings,contrast:c}}
