/* Effects synchronize IndexedDB, browser preferences or the imperative renderer after SSR. */
/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import Link from "next/link";
import {useState,useEffect,createContext,useContext} from "react";
import {QrCode,ArrowUpRight,ShieldCheck,ScanLine,Layers,Code2,Menu,Sun,Moon,Monitor} from "lucide-react";
import {Toaster} from "sonner";
import {Choice} from "./generator/controls";
import {languages,messages,Lang} from "@/i18n";
const Language=createContext<Lang>("en");export const useMessages=()=>messages[useContext(Language)];
export default function SiteShell({children,active="generator"}:{children:React.ReactNode;active?:string}){
const [ready,setReady]=useState(false);const [lang,setLang]=useState<Lang>("en"),[theme,setTheme]=useState("light"),[menu,setMenu]=useState(false);
useEffect(()=>{const l=localStorage.getItem("qrforge-language") as Lang;if(l&&messages[l])setLang(l);setTheme(localStorage.getItem("qrforge-theme")||"light");setReady(true);if("serviceWorker" in navigator&&location.hostname!=="localhost")navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";localStorage.setItem("qrforge-language",lang)},[lang]);
useEffect(()=>{const mq=matchMedia("(prefers-color-scheme: dark)");const apply=()=>{document.documentElement.dataset.theme=theme==="system"?(mq.matches?"dark":"light"):theme};apply();mq.addEventListener("change",apply);localStorage.setItem("qrforge-theme",theme);return()=>mq.removeEventListener("change",apply)},[theme]);const m=messages[lang];
return <Language.Provider value={lang}><Link href="#main" className="skip-link">Skip to content</Link><header className="topbar"><Link className="brand" href="/"><span className="brand-icon"><QrCode size={23}/></span>QRForge<sup>®</sup></Link><button className="mobile-menu secondary" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu size={18}/></button><nav className={menu?"nav-open":""} aria-label="Main navigation">{[["generator","/",m.generator],["frames","/qr-code-frames",m.frames],["scanner","/qr-scanner",m.scanner],["bulk","/bulk-qr-generator",m.bulk],["tools","/developer-tools",m.tools]].map(([key,href,label])=><Link key={key} className={active===key?"active":""} href={href}>{label}{key==="tools"&&<ArrowUpRight size={13}/>}</Link>)}</nav><div className="header-options"><Choice value={lang} onChange={v=>setLang(v as Lang)} items={languages.map(([value,label])=>({value,label}))} label="Language"/><button className="icon-button" aria-label={"Theme: "+theme+". Click to change."} title={"Theme: "+theme} onClick={()=>setTheme(theme==="light"?"dark":theme==="dark"?"system":"light")}>{theme==="light"?<Sun size={18}/>:theme==="dark"?<Moon size={18}/>:<Monitor size={18}/>}</button></div></header><main className="shell" id="main" inert={!ready} aria-busy={!ready} data-ready={ready}>{children}<section className="tool-strip"><div><div className="eyebrow">MORE WAYS TO CREATE</div><h2>Small tools. Big possibilities.</h2></div>{[{title:m.scanner,desc:"Read a code in a moment",Icon:ScanLine,url:"/qr-scanner"},{title:m.bulk,desc:"Create more, all at once",Icon:Layers,url:"/bulk-qr-generator"},{title:m.tools,desc:"Everyday essentials, in one place",Icon:Code2,url:"/developer-tools"}].map(({title,desc,Icon,url})=><Link href={url} key={url}><span className="tool-icon"><Icon size={22}/></span><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRight size={17}/></Link>)}</section><footer><Link className="brand" href="/"><QrCode size={18}/> QRForge</Link><span>Create. Customize. Scan. Anywhere.</span><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></footer></main><Toaster richColors position="bottom-center"/></Language.Provider>
}
export function LocalNote(){return <div className="under-workspace"><span><ShieldCheck size={15}/> No sign-up needed</span><span>✧ Make it your own</span><span><QrCode size={15}/> Free static QR codes</span></div>}
