"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,Upload,Copy,ScanLine} from "lucide-react";
import {toast} from "sonner";
import jsQR from "jsqr";
import {copyText,imageFrom} from "@/lib/export";
export default function Scanner(){
const [result,setResult]=useState(""),[error,setError]=useState(""),[running,setRunning]=useState(false),[busy,setBusy]=useState(false);
const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
function stop(){if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRunning(false)}
useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop())},[]);
function decode(source:CanvasImageSource,w:number,h:number){const scale=Math.min(1,1600/Math.max(w,h));const canvas=document.createElement("canvas");canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);const ctx=canvas.getContext("2d",{willReadFrequently:true})!;ctx.drawImage(source,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height);return jsQR(data.data,data.width,data.height,{inversionAttempts:"attemptBoth"})?.data}
async function scan(file?:File){if(!file)return;stop();setError("");setResult("");setBusy(true);let url="";try{if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>15000000)throw Error("Choose a PNG, JPG or WebP smaller than 15 MB.");url=URL.createObjectURL(file);const img=await imageFrom(url);if(img.width*img.height>40000000)throw Error("Image is too large.");const value=decode(img,img.width,img.height);if(!value)throw Error("No QR code found. Try a sharp, tightly cropped image.");setResult(value);toast.success("QR code scanned")}catch(e){setError((e as Error).message)}finally{if(url)URL.revokeObjectURL(url);setBusy(false)}}
async function camera(){setError("");setResult("");try{if(!navigator.mediaDevices?.getUserMedia)throw Error("Camera requires HTTPS and browser camera support. You can upload an image instead.");stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});if(!video.current)return;video.current.srcObject=stream.current;await video.current.play();setRunning(true);const tick=()=>{if(!stream.current)return;const v=video.current;if(v&&v.readyState>=2){const value=decode(v,v.videoWidth,v.videoHeight);if(value){setResult(value);stop();toast.success("QR code scanned");return}}timer.current=setTimeout(tick,250)};tick()}catch(e){stop();setError((e as Error).message)}}
let link="";try{const u=new URL(result);if(["https:","http:"].includes(u.protocol))link=u.href}catch{}
return <div className="tool-layout"><section className="panel"><div className="section-title"><ScanLine/><h2>Scan a QR code</h2></div><p className="subtle">Use your camera or upload an image. Images stay on this device.</p><div className="scanner-view"><video ref={video} playsInline muted className={running?"":"hidden-video"}/>{!running&&<ScanLine size={96}/>}</div><div className="button-row"><button className="primary" onClick={()=>running?stop():void camera()}><Camera size={18}/>{running?"Stop camera":"Start camera"}</button><label className="secondary file-button"><Upload size={18}/>Upload QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void scan(e.target.files?.[0])}/></label></div>{busy&&<p role="status">Reading image…</p>}{error&&<p className="error" role="alert">{error}</p>}</section><section className="panel"><h2>Decoded content</h2>{result?<><pre className="result-box" dir="auto">{result}</pre><div className="button-row"><button className="secondary" onClick={()=>copyText(result).then(()=>toast.success("Copied")).catch(e=>toast.error(e.message))}><Copy size={16}/>Copy result</button>{link&&<a className="primary" href={link} target="_blank" rel="noopener noreferrer">Open link</a>}</div><p className="hint">Check the destination before opening it. QRForge never opens scanned links automatically.</p></>:<p className="empty">Your decoded content will appear here.</p>}</section></div>
}
